### ISSUE TITLE
3.2 rc-2 with static analyzer gives RuntimeCompiler error

### ISSUE THREAD

**Issue by markknol** [ncannasse/hxsl#38]
I try to compile a Flambe project using the new `-D analyzer`, but I now get this error:

```
C:\HaxeToolkit\haxe\lib\hxsl/2,0,3/hxsl/RuntimeCompiler.hx:573: characters 17-20 : Unbound variable _g
```
Not sure if this is a Haxe or HXSL error.

**Comment by ncannasse** [comment]
That might interest @simn

**Comment by Simn** [comment]
Yeah, uhm, reproducible example?

**Comment by markknol** [comment]
Ill try to send a demo tomorrow. 

@aduros did you try the analyzer with flambe already too?

**Comment by markknol** [comment]
This is not relevant anymore.
