### ISSUE TITLE
why not more than 32 param?i have a shader need more

### ISSUE THREAD

**Issue by matrix3d** [ncannasse/hxsl#40]
if( paramCount == 32 )
					Context.error("Too many runtime parameters for this shader (max=32)", v.pos);

**Comment by ncannasse** [comment]
We use a 32 bit integer to store some per param info. BTW i no longer support hxsl2, development has been moved to https://github.com/ncannasse/heaps (hxsl3)

**Comment by matrix3d** [comment]
oh,thanks rp.i will move to look at the hxsl3.
