### ISSUE TITLE
why not m33 ,now it is dp3

### ISSUE THREAD

**Issue by matrix3d** [ncannasse/hxsl#41]
Test2.hx:20: vertex:
	mov t0.xyz, c4.xxx
	dp3 t1.x, t0.xyz, c0
	dp3 t1.y, t0.xyz, c1
	dp3 t1.z, t0.xyz, c2
	mov out, t1.xyzz
fragment:
	mov out, c0.xxxx

**Comment by ncannasse** [comment]
m33 is just a macro, this will not change much
